name            = "portal-cms-api"
main            = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
FIREBASE_PROJECT_ID = "portal-cms-emk"
FIREBASE_API_KEY    = "AIzaSyCPyLBMiApOUs3L2K3SVPeF_Z9Klh5jp94"

# GOOGLE_SERVICE_ACCOUNT_EMAIL / GOOGLE_PRIVATE_KEY は不要になりました
